package com.digitaledu.core.designsystem.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val ProsvetLightColorScheme = lightColorScheme(
    primary = Color(0xFF0058BE),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF2170E4),
    onPrimaryContainer = Color(0xFFFEFCFF),
    secondary = Color(0xFF006B5F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF6DF5E1),
    onSecondaryContainer = Color(0xFF006F64),
    tertiary = Color(0xFF924700),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB75B00),
    onTertiaryContainer = Color(0xFFFFFBFF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF7F9FB),
    onBackground = Color(0xFF191C1E),
    surface = Color(0xFFF7F9FB),
    onSurface = Color(0xFF191C1E),
    surfaceVariant = Color(0xFFE0E3E5),
    onSurfaceVariant = Color(0xFF424754),
    outline = Color(0xFF727785),
    outlineVariant = Color(0xFFC2C6D6),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2D3133),
    inverseOnSurface = Color(0xFFEFF1F3),
    inversePrimary = Color(0xFFADC6FF),
    surfaceDim = Color(0xFFD8DADC),
    surfaceBright = Color(0xFFF7F9FB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F4F6),
    surfaceContainer = Color(0xFFECEEF0),
    surfaceContainerHigh = Color(0xFFE6E8EA),
    surfaceContainerHighest = Color(0xFFE0E3E5),
)
