name: DigitalEduiOS

options:
  minimumXcodeGenVersion: 2.40.0

targets:
  DigitalEduiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DigitalEduiOSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.digitaledu.ios
        PRODUCT_NAME: DigitalEduiOS
        INFOPLIST_FILE: DigitalEduiOSApp/Info.plist
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/Shared.framework
