"""Add LessonReference model

Revision ID: 9845f9f517a3
Revises: 0008_fix_user_sessions
Create Date: 2026-02-11 21:03:30.793482
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9845f9f517a3"
down_revision: Union[str, None] = "0008_fix_user_sessions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("key_points", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("code_snippets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_references_lesson_id"), "lesson_references", ["lesson_id"], unique=False
    )
    op.drop_constraint(op.f("courses_slug_key"), "courses", type_="unique")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.drop_constraint(op.f("qr_login_tokens_token_hash_key"), "qr_login_tokens", type_="unique")
    op.drop_index(op.f("ix_qr_login_tokens_token_hash"), table_name="qr_login_tokens")
    op.create_index(
        op.f("ix_qr_login_tokens_token_hash"), "qr_login_tokens", ["token_hash"], unique=True
    )
    op.drop_constraint(op.f("users_phone_hash_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=False)
    op.create_unique_constraint(
        op.f("users_phone_hash_key"), "users", ["phone_hash"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_qr_login_tokens_token_hash"), table_name="qr_login_tokens")
    op.create_index(
        op.f("ix_qr_login_tokens_token_hash"), "qr_login_tokens", ["token_hash"], unique=False
    )
    op.create_unique_constraint(
        op.f("qr_login_tokens_token_hash_key"),
        "qr_login_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("courses_slug_key"), "courses", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_lesson_references_lesson_id"), table_name="lesson_references")
    op.drop_table("lesson_references")
    # ### end Alembic commands ###
