"""Add LessonReference model

Revision ID: 9845f9f517a3
Revises: 0008_fix_user_sessions
Create Date: 2026-02-11 21:03:30.793482
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9845f9f517a3"
down_revision: Union[str, None] = "0008_fix_user_sessions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("lesson_references"):
        op.create_table(
            "lesson_references",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("lesson_id", sa.UUID(), nullable=False),
            sa.Column("title", sa.String(length=255), nullable=False),
            sa.Column("summary_text", sa.Text(), nullable=False),
            sa.Column("key_points", sa.ARRAY(sa.String()), nullable=False),
            sa.Column("code_snippets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    lesson_ref_indexes = {idx["name"] for idx in inspector.get_indexes("lesson_references")}
    lesson_ref_idx = op.f("ix_lesson_references_lesson_id")
    if lesson_ref_idx not in lesson_ref_indexes:
        op.create_index(lesson_ref_idx, "lesson_references", ["lesson_id"], unique=False)

    if inspector.has_table("courses"):
        courses_uniques = {
            c["name"] for c in inspector.get_unique_constraints("courses") if c.get("name")
        }
        courses_slug_unique = op.f("courses_slug_key")
        if courses_slug_unique in courses_uniques:
            op.drop_constraint(courses_slug_unique, "courses", type_="unique")

        courses_indexes = {idx["name"] for idx in inspector.get_indexes("courses")}
        courses_slug_idx = op.f("ix_courses_slug")
        if courses_slug_idx in courses_indexes:
            op.drop_index(courses_slug_idx, table_name="courses")
        op.create_index(courses_slug_idx, "courses", ["slug"], unique=True)

    if inspector.has_table("qr_login_tokens"):
        qr_uniques = {
            c["name"]
            for c in inspector.get_unique_constraints("qr_login_tokens")
            if c.get("name")
        }
        qr_unique_name = op.f("qr_login_tokens_token_hash_key")
        if qr_unique_name in qr_uniques:
            op.drop_constraint(qr_unique_name, "qr_login_tokens", type_="unique")

        qr_indexes = {idx["name"] for idx in inspector.get_indexes("qr_login_tokens")}
        qr_idx = op.f("ix_qr_login_tokens_token_hash")
        if qr_idx in qr_indexes:
            op.drop_index(qr_idx, table_name="qr_login_tokens")
        op.create_index(qr_idx, "qr_login_tokens", ["token_hash"], unique=True)

    if inspector.has_table("users"):
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        if "phone_hash" in user_columns:
            users_uniques = {
                c["name"] for c in inspector.get_unique_constraints("users") if c.get("name")
            }
            users_unique_name = op.f("users_phone_hash_key")
            if users_unique_name in users_uniques:
                op.drop_constraint(users_unique_name, "users", type_="unique")

            users_indexes = {idx["name"] for idx in inspector.get_indexes("users")}
            users_idx = op.f("ix_users_phone_hash")
            if users_idx in users_indexes:
                op.drop_index(users_idx, table_name="users")
            op.create_index(users_idx, "users", ["phone_hash"], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=False)
    op.create_unique_constraint(
        op.f("users_phone_hash_key"), "users", ["phone_hash"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_qr_login_tokens_token_hash"), table_name="qr_login_tokens")
    op.create_index(
        op.f("ix_qr_login_tokens_token_hash"), "qr_login_tokens", ["token_hash"], unique=False
    )
    op.create_unique_constraint(
        op.f("qr_login_tokens_token_hash_key"),
        "qr_login_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("courses_slug_key"), "courses", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_lesson_references_lesson_id"), table_name="lesson_references")
    op.drop_table("lesson_references")
    # ### end Alembic commands ###
